apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
spec:
  selector:
    matchLabels:
      app: nginx-1
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
        - image: nginx
          name: nginx
          # command: ["sh", "-c", "sleep 30 && /docker-entrypoint.sh nginx -g daemon off;"]
          command: ["sh", "-c", "sleep 30 && /docker-entrypoint.sh nginx -g \"daemon off;\""]
          startupProbe:
            initialDelaySecond: 35
            periodSeconds: 5
            httpGet:
              path: /
              port: 80
